name: CodeCov
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload coverage to CodeCov
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install .[cov]
    - name: Run tests and collect coverage
      run: |
        coverage run manage.py test
        coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
